CREATE TABLE WRLDC_REST_SUBSET.FILE_INFO (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    regulation_name VARCHAR2(250) NOT NULL,
    reg_type VARCHAR2(15) NOT NULL,
    amendment_no NUMBER(25) NOT NULL,
    notification_date DATE NOT NULL,
    effective_date DATE NOT NULL,
    repeal_date DATE,
    keyWords_admin VARCHAR2(250) NOT NULL,
    doc_ref_no NUMBER(25) NOT NULL,
    pdf_file_name VARCHAR2(8) NOT NULL,
    cerc_Site_pdf_link VARCHAR2(100)
);